{{- if and .Values.networkExplorer.enabled .Values.networkExplorer.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ include "splunk-otel-collector-kernel-collector.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "splunk-otel-collector-kernel-collector.fullname" . }}
rules:
{{- if eq (include "splunk-otel-collector.distribution" .) "openshift" }}
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas
  verbs:
  - get
  - list
  - watch
{{- end }}
- apiGroups:
  - policy
  resourceNames:
  - {{ include "splunk-otel-collector-kernel-collector.fullname" . }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end -}}
