clusterName: CHANGEME
splunkObservability:
  realm: CHANGEME
  accessToken: CHANGEME

agent:
  config:
    extensions:
      pprof:
    service:
      extensions:
        - health_check
        - k8s_observer
        - zpages
        - pprof
